apiVersion: v1
kind: Namespace
metadata:
  name: tls-updater-test
spec:
  finalizers:
    - kubernetes
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-2
  namespace: tls-updater-test
data:
  tls.crt: ""
  tls.key: ""
type: kubernetes.io/tls
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-3
  namespace: tls-updater-test
data:
  tls.crt: ""
  tls.key: ""
type: kubernetes.io/tls
---
kind: Secret
apiVersion: v1
metadata:
  name: secret-1
  namespace: tls-updater-test
  labels:
    tls-updater: 'true'
  annotations:
    tls-updater-dests: secret-2,secret-3
data:
  tls.crt: dGxzLmNydA==
  tls.key: dGxzLmtleQ==
type: kubernetes.io/tls
